server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:haochenchn/microservicecloud.git #GitHub上面的git仓库名字
          search-paths: config-repo
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-config
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
